<?xml version="1.0"?>
<package format="3">
  <name>mushr_sim_interfaces</name>
  <version>0.0.0</version>
  <description>Interfaces for MuSHR simulation</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <depend>std_msgs</depend>

  <member_of_group>rosidl_interface_packages</member_of_group>
<export>
  <build_type>ament_cmake</build_type>
</export>

</package>
