services:
  mushr_humble:
    image: dbzfan2012/mushr-humble:${MUSHR_OS_TYPE}
    runtime: nvidia
    network_mode: host
    privileged: true
    devices:
      - "/dev:/dev"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - /usr/bin/tegrastats:/usr/bin/tegrastats
      - /etc/udev:/etc/udev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /dev/input:/dev/input
      - ${MUSHR_WS_PATH}/colcon_ws:/root/colcon_ws
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - MUSHR_REAL_ROBOT=${MUSHR_REAL_ROBOT}
    stdin_open: true
    tty: true
