services:
  mushr_jazzy:
    image: dbzfan2012/mushr-jazzy:${MUSHR_OS_TYPE}
    privileged: true
    network_mode: host
    volumes:
      - ${MUSHR_WS_PATH}/colcon_ws:/root/colcon_ws
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - MUSHR_REAL_ROBOT=${MUSHR_REAL_ROBOT}
    stdin_open: true
    tty: true
